version: '3'

services:
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: ${MYSQL_PORT}
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d/
    networks:
      - erp
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '--port',
          '${MYSQL_PORT}',
          '-u ${MYSQL_USER}',
          '-p ${MYSQL_PASSWORD}',
        ]
      timeout: 5s
      retries: 10

volumes:
  mysql-volume:

networks:
  erp:
    driver: bridge
